# Generated by Django 3.0.6 on 2020-05-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_auto_20200506_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorplanscommercialpremises',
            options={'verbose_name': 'Планировка Коммерческого помещения', 'verbose_name_plural': 'Планировки Коммерческого помещения'},
        ),
        migrations.AlterModelOptions(
            name='imagescommercialpremises',
            options={'verbose_name': 'Изображение Коммерческого помещения', 'verbose_name_plural': 'Изображения Коммерческого помещения'},
        ),
        migrations.AlterModelOptions(
            name='imagesresidentialcomplex',
            options={'verbose_name': 'Изображение Жилого Комплекса', 'verbose_name_plural': 'Изображения Жилого Комплекса'},
        ),
        migrations.AlterField(
            model_name='floorplanscommercialpremises',
            name='alt_attr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание, alt'),
        ),
        migrations.AlterField(
            model_name='imagescommercialpremises',
            name='alt_attr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание, alt'),
        ),
        migrations.AlterField(
            model_name='imagesresidentialcomplex',
            name='alt_attr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание, alt'),
        ),
    ]
