# Generated by Django 3.0.6 on 2020-05-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_auto_20200506_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameOfNearestMetro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Название ближайщего метро',
                'verbose_name_plural': 'Названии ближайщих метро',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='relativelocation',
            options={'ordering': ['name'], 'verbose_name': 'Расположение', 'verbose_name_plural': 'Расположения'},
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='kw',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='кВт'),
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='max_area',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Площадь до, м'),
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='min_area',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Площадь от, м'),
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='several_floors',
            field=models.BooleanField(default=False, verbose_name='Помещение с несколькими этажами'),
        ),
        migrations.AlterField(
            model_name='commercialpremises',
            name='max_payback',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Окупаемость до, мес'),
        ),
        migrations.AlterField(
            model_name='commercialpremises',
            name='min_payback',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Окупаемость от, мес'),
        ),
        migrations.RemoveField(
            model_name='commercialpremises',
            name='relative_location',
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='relative_location',
            field=models.ManyToManyField(blank=True, default=None, related_name='relativelocation', to='realestate.RelativeLocation', verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='name_of_nearest_metro',
            field=models.ManyToManyField(blank=True, default=None, related_name='nameofnearestmetro', to='realestate.NameOfNearestMetro', verbose_name='Название ближайщего метро'),
        ),
    ]
