# Generated by Django 3.0.6 on 2020-05-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_auto_20200506_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialpremises',
            name='building_commercial_premise',
        ),
        migrations.RemoveField(
            model_name='commercialpremises',
            name='finished_commercial_premise',
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='ready_commercial_premise',
            field=models.CharField(blank=True, choices=[('building', 'Строящее'), ('finished', 'Готовое')], db_index=True, max_length=255, verbose_name='Готовность помещения'),
        ),
    ]
