# Generated by Django 3.0.6 on 2020-05-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_auto_20200506_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nameofnearestmetro',
            options={'ordering': ['name'], 'verbose_name': 'Название ближайщего метро', 'verbose_name_plural': 'Названии ближайщего метро'},
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='max_storeys',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Этажность max'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='min_storeys',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Этажность min'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='number_of_storeys',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='one_or_many_buildings',
            field=models.BooleanField(default=False, verbose_name='В ЖК несколько строений'),
        ),
    ]
