# Generated by Django 3.0.6 on 2020-05-06 12:30

from django.db import migrations, models
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_auto_20200506_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to=realestate.models.generate_url_for_logo_image, verbose_name='Логотип застройщика'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to=realestate.models.generate_url_for_logo_image, verbose_name='Логотип ЖК'),
        ),
        migrations.RemoveField(
            model_name='commercialpremises',
            name='floor',
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='floor',
            field=models.ManyToManyField(blank=True, default=None, related_name='floorcommercialpremises', to='realestate.FloorInBuilding', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='site_developer',
            field=models.URLField(blank=True, default=None, max_length=300, null=True, verbose_name='Сайт застройщика/Жилого комплекса'),
        ),
    ]
