# Generated by Django 3.0.6 on 2020-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_auto_20200506_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeadlineNewBuilding',
            new_name='Deadline',
        ),
        migrations.RenameModel(
            old_name='NameOfNearestMetro',
            new_name='NamesOfMetroStations',
        ),
        migrations.AlterModelOptions(
            name='namesofmetrostations',
            options={'ordering': ['name'], 'verbose_name': 'Станция метро', 'verbose_name_plural': 'Станции метро'},
        ),
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='name_of_nearest_metro',
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='metro_stations',
            field=models.ManyToManyField(blank=True, default=None, related_name='metrostations', to='realestate.NamesOfMetroStations', verbose_name='Название ближайщего метро'),
        ),
    ]
