# Generated by Django 3.0.6 on 2020-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_auto_20200506_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='namesofmetrostations',
            name='distance_to_center',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расстояние до центра'),
        ),
        migrations.AddField(
            model_name='namesofmetrostations',
            name='sub_text_distance_to_center',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текс для тултипа'),
        ),
        migrations.AlterField(
            model_name='namesofmetrostations',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
