# Generated by Django 3.0.6 on 2020-05-06 14:11

from django.db import migrations, models
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_apartmentdecoration_city_materialwallsofhouse_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('icon', models.FileField(blank=True, null=True, upload_to=realestate.models.generate_url_for_image, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Инфраструктура',
                'verbose_name_plural': 'Инфраструктура',
                'ordering': ['name'],
            },
        ),
    ]
