# Generated by Django 3.0.6 on 2020-05-06 14:55

from django.db import migrations, models
import django.db.models.deletion
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0012_infrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Количество комнат',
                'verbose_name_plural': 'Количество комнат',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='floorinbuilding',
            options={'ordering': ['num_floor'], 'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажи'},
        ),
        migrations.CreateModel(
            name='ResidentialPremise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать, Да/Нет')),
                ('area', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Площадь')),
                ('min_area', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Площадь от, м')),
                ('max_area', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Площадь до, м')),
                ('price', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Цена')),
                ('min_price', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Цена от, м')),
                ('max_price', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Цена до, м')),
                ('floor', models.ManyToManyField(blank=True, default=None, related_name='floorresidentialpremise', to='realestate.FloorInBuilding', verbose_name='Этаж')),
                ('number_rooms', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numberrooms', to='realestate.NumberOfRooms', verbose_name='Количество комнат')),
                ('res_complex', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescomplex', to='realestate.ResidentialComplex', verbose_name='Жилой комплекс')),
            ],
            options={
                'verbose_name': 'Жилое помещение',
                'verbose_name_plural': 'Жилые помещения',
            },
        ),
        migrations.CreateModel(
            name='FloorPlansResidentialPremise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_attr', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание, alt')),
                ('image', models.FileField(blank=True, null=True, upload_to=realestate.models.generate_url_for_image, verbose_name='Планировка Жилого помещения')),
                ('residential_premises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.ResidentialPremise', verbose_name='Жилое помещение')),
            ],
            options={
                'verbose_name': 'Планировка Жилого помещения',
                'verbose_name_plural': 'Планировки Жилого помещения',
            },
        ),
    ]
