# Generated by Django 3.0.6 on 2020-05-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_auto_20200506_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassNewBuilding',
            new_name='ClassOfHousing',
        ),
        migrations.AlterModelOptions(
            name='classofhousing',
            options={'ordering': ['name'], 'verbose_name': 'Класс Жилья', 'verbose_name_plural': 'Классы Жилья'},
        ),
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='class_new_building',
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='class_of_housing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classofhousing', to='realestate.ClassOfHousing', verbose_name='Класс Новостройки'),
        ),
    ]
