# Generated by Django 3.0.6 on 2020-05-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_auto_20200506_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialpremises',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_com_premises', to='realestate.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_com_premises', to='realestate.Region', verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='apart_decoration',
            field=models.ManyToManyField(blank=True, default=None, related_name='apart_decoration_res_complex', to='realestate.ApartmentDecoration', verbose_name='Отделка'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_res_complex', to='realestate.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='infrastructure',
            field=models.ManyToManyField(blank=True, default=None, related_name='infrastructure_res_complex', to='realestate.Infrastructure', verbose_name='Инфраструктура'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='is_visible_video',
            field=models.BooleanField(default=False, verbose_name='Показывать видео'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='material_walls',
            field=models.ManyToManyField(blank=True, default=None, related_name='material_walls_res_complex', to='realestate.MaterialWallsOfHouse', verbose_name='Материал стен дома'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_res_complex', to='realestate.Region', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='VideoResidentialComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_on_video', models.URLField(blank=True, default=None, max_length=2000, null=True, verbose_name='Ссылка на видео')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.ResidentialComplex', verbose_name='Жилой Комплекс')),
            ],
            options={
                'verbose_name': 'Видео Жилого Комплекса',
                'verbose_name_plural': 'Видео Жилого Комплекса',
                'ordering': ['id'],
            },
        ),
    ]
