# Generated by Django 3.0.6 on 2020-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0015_auto_20200507_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='alt_attr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='img alt'),
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='alt_attr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='img alt'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='alt_attr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='img alt'),
        ),
        migrations.AlterField(
            model_name='floorplanscommercialpremises',
            name='alt_attr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='img alt'),
        ),
        migrations.AlterField(
            model_name='floorplansresidentialpremise',
            name='alt_attr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='img alt'),
        ),
        migrations.AlterField(
            model_name='imagescommercialpremises',
            name='alt_attr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='img alt'),
        ),
        migrations.AlterField(
            model_name='imagesresidentialcomplex',
            name='alt_attr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='img alt'),
        ),
    ]
